package com.kkrepo.blog.repository;

import com.kkrepo.blog.domain.Article;
import com.kkrepo.blog.domain.ArticleExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;

public interface ArticleMapper {
    long countByExample(ArticleExample example);

    int deleteByExample(ArticleExample example);

    int deleteByPrimaryKey(Long id);

    int insert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int insertSelective(@Param("record") Article record, @Param("selective") Article.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Article selectOneByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Article selectOneByExampleSelective(@Param("example") ArticleExample example, @Param("selective") Article.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Article selectOneByExampleWithBLOBs(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    List<Article> selectByExampleSelective(@Param("example") ArticleExample example, @Param("selective") Article.Column ... selective);

    List<Article> selectByExampleWithBLOBs(ArticleExample example);

    List<Article> selectByExample(ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    Article selectByPrimaryKeySelective(@Param("id") Long id, @Param("selective") Article.Column ... selective);

    Article selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example, @Param("selective") Article.Column ... selective);

    int updateByExampleWithBLOBs(@Param("record") Article record, @Param("example") ArticleExample example);

    int updateByExample(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int updateByPrimaryKeySelective(@Param("record") Article record, @Param("selective") Article.Column ... selective);

    int updateByPrimaryKeyWithBLOBs(Article record);

    int updateByPrimaryKey(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsert(@Param("list") List<Article> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchInsertSelective(@Param("list") List<Article> list, @Param("selective") Article.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsert(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExample(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleSelective(@Param("record") Article record, @Param("example") ArticleExample example, @Param("selective") Article.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertByExampleWithBLOBs(@Param("record") Article record, @Param("example") ArticleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertSelective(@Param("record") Article record, @Param("selective") Article.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int upsertWithBLOBs(Article record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsert(@Param("list") List<Article> list);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertSelective(@Param("list") List<Article> list, @Param("selective") Article.Column ... selective);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_article
     *
     * @mbg.generated
     * @project https://github.com/itfsw/mybatis-generator-plugin
     */
    int batchUpsertWithBLOBs(@Param("list") List<Article> list);

    @Select("select id,title from tb_article where state = #{state} order by id desc limit #{limit}")
    List<Article> selectLatestIdAndName(@Param("state") String state, @Param("limit") int limit);

    @Select("select distinct DATE_FORMAT(publish_time, '%Y-%m') from tb_article where state = #{state} order by DATE_FORMAT(publish_time, '%Y-%m') desc")
    List<String> queryArchivesDates(@Param("state") String state);

    @Select("select id,title,publish_time publishTime from tb_article where state = #{state} and publish_time like CONCAT ('%', #{publishTime}, '%')")
    List<Article> queryArchivesByDate(@Param("publishTime") String publishTime, @Param("state") String state);

    @Select("select id,title,cover,author,description,create_time as createTime from tb_article where id in(select article_id from tb_article_category where category_id = #{categoryId}) order by id desc")
    List<Article> selectByCategory(@Param("categoryId") long categoryId);

    @Select("select id,title,cover,author,description,create_time as createTime from tb_article where state = #{state} and id in(select article_id from tb_article_category where category_id = #{categoryId}) order by id desc limit #{offset},#{limit}")
    List<Article> selectByCategoryAndState(@Param("categoryId") long categoryId, @Param("offset") int offset, @Param("limit") int limit, @Param("state") String state);

    @Select("select id,title,cover,author,description,create_time as createTime from tb_article where id in(select article_id from tb_article_tag where tag_id = #{tagId}) order by id desc")
    List<Article> selectByTag(@Param("tagId") long tagId);

    @Select("select id,title,cover,author,description,create_time as createTime from tb_article where state = #{state} and id in(select article_id from tb_article_tag where tag_id = #{tagId}) order by id desc limit #{offset},#{limit}")
    List<Article> selectByTagAndState(@Param("tagId") long tagId, @Param("offset") int offset, @Param("limit") int limit,  @Param("state") String state);

    @Select("select count(*) from tb_article where state = #{state} and id in(select article_id from tb_article_category where category_id = #{categoryId})")
    int countByCategoryAndState(@Param("categoryId") int categoryId, @Param("state") String state);

    @Select("select count(*) from tb_article where state = #{state} and id in(select article_id from tb_article_tag where tag_id = #{tagId})")
    int countByTagAndState(@Param("tagId") int tagId, @Param("state") String state);
}
